services:
  api-gpu:
    build: ./Dockerfile.gpu
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]